project:
  type: website

website:
  title: "Data Skills Portfolio Program"
  navbar: 
    background: primary
    search: true
    left: 
      - text: "Home"
        href: index.qmd
      - text: "What is the DSP Program?"
        href: intro.qmd
        
  
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



